name: PCIPG
channels:
  - pytorch
  - nvidia
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/r/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2025.1.31=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.55=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=3
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.5=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py312h06a4308_0
  - numpy=2.0.1=py312hc5e2394_1
  - numpy-base=2.0.1=py312h0da6c21_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=11.1.0=py312hcea889d_0
  - pip=25.0=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - setuptools=75.8.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py312_cu121
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu121
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.3.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - anyio==4.9.0
      - attrs==25.1.0
      - bio==1.7.1
      - biopython==1.85
      - biothings-client==0.4.1
      - biotite==1.1.0
      - biotraj==1.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gprofiler-official==1.0.0
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.13.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markdown==3.7
      - matplotlib==3.10.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - mygene==3.2.2
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - platformdirs==4.3.7
      - pooch==1.8.2
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - scikit-learn==1.7.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - tzdata==2025.1
      - werkzeug==3.1.3
      - yarl==1.18.3
prefix: /home/hp/anaconda3/envs/pytorch
